resources:
- name: concourse-repo
  type: git
  source:
    uri: https://github.com/amacharla/concourse-demo.git

- name: concourse-gcc-image
  type: docker-image
  source:
    email: ((docker-email)) 
    username: ((docker-username))
    password: ((docker-password)) 
    repository: amacharla/concourse-gcc

jobs:
- name: publish
  public: true
  plan:
  - get: concourse-repo
    trigger: true
  - put: concourse-gcc-image 
    params:
      build: concourse-repo/docker
  - task: run_program
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amacharla/concourse-gcc
      run:
        path: gcc
        args: [main.c]
