resources:
- name: concourse-repo
  type: git
  source:
    uri: https://github.com/amacharla/concourse-demo.git

jobs:
- name: publish
  public: true
  plan:
  - get: concourse-repo
    trigger: true
  - task: run_program
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amacharla/concourse-gcc
      inputs:
        - name: concourse-repo
      run:
        path: sh
        args:
          - -exc
          - |
            gcc concourse-repo/docker/main.c
            ./a.out
